image: python:latest

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - python -V

stages:
  - test

test:
  stage: test
  before_script:
    - pip install -r requirements/requirements.txt
    - pip install coverage
  script:
    - coverage run --source='.' manage.py test the-app-you-want-to-test
      - coverage report
  artifacts:
    paths:
      - public/coverage
